# Generated by Django 3.2.5 on 2021-08-19 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs1_education', '0002_auto_20210818_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyquestion',
            old_name='question',
            new_name='text',
        ),
    ]
