# Generated by Django 3.2.5 on 2021-08-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs1_education', '0003_rename_question_surveyquestion_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.TextField(default=str),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='experiment',
            unique_together={('question_order', 'survey_question_order', 'consent_form')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('text', 'code')},
        ),
    ]
