# Generated by Django 3.2.5 on 2021-08-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs1_education', '0004_auto_20210819_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='post_text',
        ),
        migrations.AddField(
            model_name='question',
            name='pre_text',
            field=models.TextField(default=str),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('pre_text', 'post_text', 'code')},
        ),
    ]
