# Generated by Django 3.2.5 on 2021-09-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs1_education', '0009_auto_20210824_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='farewell_message',
            field=models.TextField(default='Thank you for participating in this experiment.'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='hint_timeout',
            field=models.IntegerField(default=60000),
        ),
    ]
