# Generated by Django 3.2.5 on 2021-10-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs1_education', '0011_experiment_random_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('activity', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='interaction',
        ),
        migrations.AddField(
            model_name='participant',
            name='session_key',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
