# Generated by Django 3.2.5 on 2021-10-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs1_education', '0012_auto_20211013_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='consent',
            field=models.CharField(default=str, max_length=1000),
        ),
    ]
