# Generated by Django 3.2.5 on 2021-10-13 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs1_education', '0013_alter_participant_consent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('code', 'name', 'session_key', 'experiment_id')},
        ),
    ]
